<h2>OBJETIVOS</h2>
<div style="text-align: justify">
<p><font><strong><span>OBJETIVO 1 <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>:<span>&nbsp; </span></span></strong></font><span><font>Consolidar<span>&nbsp; </span>a la UNSM como un centro superior de estudios de calidad acad&eacute;mica que forme profesionales de acuerdo con las necesidades y desarrollo de la regi&oacute;n y el pa&iacute;s</font>.</span></p>
<p><font><strong><span>OBJETIVO 2 <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>:<span>&nbsp; </span></span></strong></font><span><font>Desarrollar proyectos de investigación científica y tecnológica de carácter multidisciplinario que aporte al desarrollo de la región y del país</font>.</span></p>
<p><font><strong><span>OBJETIVO 3 <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>:<span>&nbsp; </span></span></strong></font><span><font>Promover proyectos de extensión y proyección social universitaria en base a resultados de la investigación</font>.</span></p>
<p><font><strong><span>OBJETIVO 4 <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>:<span>&nbsp; </span></span></strong></font><span><font>Contribuir a mejorar la calidad de la enseñanza – aprendizaje con la modernización e implementación de laboratorios, bibliotecas y el uso apropiado de Nuevas Tecnologías de Información y Comunicación</font>.</span></p>
<p><font><strong><span>OBJETIVO 5 <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>:<span>&nbsp; </span></span></strong></font><span><font>Continuar con la actualización y perfeccionamiento del personal docente para mejorar su desempeño académico de calidad</font>.</span></p>
<p><font><strong><span>OBJETIVO 6 <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>:<span>&nbsp; </span></span></strong></font><span><font>Continuar con el desarrollo de la infraestructura universitaria para contar con ambientes físicos adecuados que favorezcan el proceso de enseñanza – aprendizaje</font>.</span></p>
<p><font><strong><span>OBJETIVO 7 <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>:<span>&nbsp; </span></span></strong></font><span><font>Mejorar los servicios de bienestar universitario que permita la atención alimentaria, médica, odontológica, transporte y otros servicios que brinda la Universidad</font>.</span></p>
</div>